[package]
name = "bson"
version = "0.3.0"
authors = ["Y. T. Chung <zonyitoo@gmail.com>"]
description = "Encoding and decoding support for BSON in Rust"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/zonyitoo/bson-rs"

[lib]
name = "bson"

[dependencies]
byteorder = "0.3"
chrono = "0.2"
libc = "0.1"
rand = "0.3"
rust-crypto = "0.2.31"
rustc-serialize = "0.3"
serde = "0.8"
time = "0.1"
linked-hash-map = "0.0.9"

[dependencies.num]
version = "~0.1.27"
default-features = false
