[package]
name = "bson-rs"
version = "0.0.2"
authors = ["Y. T. Chung <zonyitoo@gmail.com>"]
description = "Encoding and decoding support for BSON in Rust"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/zonyitoo/bson-rs"

[lib]
name = "bson"

[dependencies]
chrono = "*"
byteorder = "*"
rustc-serialize = "*"
